spring:
  application:
    name: skill
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/crawler?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
server:
  port: 9111

mybatis:
  configuration:
    map-underscore-to-camel-case:true
mybatis-plus:
  mapper-locations: mapper/*xml
  type-aliases-package: com.application.skill.crud.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
