CREATE TABLE
IF NOT EXISTS t_user(
    `id` VARCHAR (32) NOT NULL COMMENT '主键',
    `userName` VARCHAR (32) DEFAULT NULL COMMENT '用户名',
   `sex` TINYINT (1) NOT NULL DEFAULT '0' NULL COMMENT '0:男  1：女 ',
    `phoneNumBer` VARCHAR (32) DEFAULT NULL COMMENT '手机号码'
    PRIMARY KEY (`ID`),
) ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT = '用户名';
